### PR TITLE
Install Modules for Postgres 9.1

### PR DESCRIPTION
**Pull request by benhamill**
In Postgres 9.1, contrib modules got moved over to the [extension system](http://www.postgresql.org/docs/9.1/static/sql-createextension.html). In order to make Texticle compatible with the newer version, we should make the rake task that installs trigram detect the version and act accordingly. It was complex enough that I felt like it deserved its own object and, in the process, I realized it was easily genericizable (by the power of my BA in Linguistics, I declare this is a word). Thoughts, anyone?

(This is a port of [this pull request](https://github.com/tenderlove/texticle/pull/68).)

### CODE REVIEW

**Comment by phaza** [comment]
I don't think this will work on Heroku with their shared db plan.

I'm testing it now, and while heroku pg:info returns 9.1._, `pg_config --version` in the heroku console returns 8._ which leads me to think this wont work.

Not sure how it can be resolved either.

**Comment by benhamill** [comment]
It is my understanding, though this could be flawed, that Heroku is, in fact, running an older version of Postgres. I think 8.something, which means that it doesn't even have the normal search stuff built in. But I've not tested it... Is it possible that search stuff is already installed on Heroku?

In any case, it's dismaying that Postgres isn't consistent about reporting version numbers. Maybe there's a way to connect to the DB and ask it directly. I'll look into it. I also may see about assembling a test heroku app and try some stuff out. Thanks.

**Comment by benhamill** [comment]
Man. 2 seconds of Google: `SELECT version();`. Hopefully that'll be more reliable.

**Comment by phaza** [comment]
The main problem will be figuring out the sharedir to load the extensions from. Not sure how that can be easily solved unless it's left as a configuration option for the user.

**Comment by benhamill** [comment]
Hmm. So I did a little test. I'm not sure what this portends, but here's the output I'm seeing on one of my heoku apps:

```
$ heroku run rails c
Running rails c attached to terminal... up, run.1
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/01/04/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/01/04/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/01/04/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
Loading production environment (Rails 3.2.1)
irb(main):001:0> r = User.connection.execute('SELECT version();')
   (5.8ms)  SELECT version();
=> #<PGresult:0x00000003e93a60>
irb(main):002:0> r.to_a
=> [{"version"=>"PostgreSQL 8.3.11 on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.1.2 20061115 (prerelease) (Debian 4.1.1-21)"}]
irb(main):003:0> `pg_config --version`
=> "PostgreSQL 8.4.9\n"
```

So... They at least both agree that they're running Postgres 8... And I think that they don't have the contrib stuff up there anyway... I don't know. Part of me wants to be kind of a jerk and say that if your Postgres install is broken like this (and it is not hard to do, I have done it), you should fix it so that `pg_config` knows about the version of Postgres you're actually running against.

The other part of me realizes that not working on Heroku will seem really stupid to a lot of people. But if they don't have the contrib stuff up there, then installing plugins won't work anyway. Evidence, by the way, that contrib stuff is not installed:

```
$ heroku run 'find /usr/share/postgresql/'
Running find /usr/share/postgresql/ attached to terminal... up, run.1
/usr/share/postgresql/
/usr/share/postgresql/8.4
/usr/share/postgresql/8.4/man
/usr/share/postgresql/8.4/man/man1
/usr/share/postgresql/8.4/man/man1/pg_config.1
```

**Comment by phaza** [comment]
The thing is that database is not on localhost, it's on url host pointed to by $DATABASE_URL.

**Comment by benhamill** [comment]
Oh of course. Bleh. I guess that's why the 9.1 way is better than the previous way... It leaves finding the package up to the DB, which means it'll be looking on the same machine. Thanks for this discussion, by the way, I'll noodle some more on it. Or would love a suggestion.

**Comment by benhamill** [comment]
So, I just realized that... I haven't ever run this in production. I don't think I'd recommend it. Do folks feel like it's reasonable to plaster a warning on this task that mentions it's for your local box only ('development' and 'test' in Rails)? In production, you're almost always going to be dealing with a separate box running your DB, no? And so have to shell in and run these commands manually against Postgres.

Thoughts?

**Comment by benhamill** [comment]
So Heroku has updated to 9.1.6 now. It seems like we could safely do this thing, for 9.1 if we modify it to ask the DB about its version. I don't think there's anything we can do about Heroku for helping install stuff prior to 9.1, since we can't guess the right paths on a remote machine, but 9.1 doesn't need the path, anyway.

**Pull request merged**
