### PR TITLE
Update gemspec to allow Rails 4 support

### PR DESCRIPTION
**Pull request by olivierlacan**
Quickly tested `#advanced_search` and `#fuzzy_search` and everything worked fine under the latest Rails 4 from [rails/master](http://github.com/rails/rails)

Used the same solution as [haml-rails](https://github.com/indirect/haml-rails/blob/master/haml-rails.gemspec#L21) did recently.

### CODE REVIEW

**Comment by benhamill** [comment]
Not bad. I want to play around with it, myself, a bit before I merge, but this is, in general, a good idea. Thanks.

**Comment by olivierlacan** [comment]
Please do. I feel a bit weird submitting this without tests though. Is there a simple way to test against multiple Rails?

**Comment by benhamill** [comment]
The only thing that springs to mind for me is to run the tests against different environments on a CI machine. Possibly we should look into that. I dunno.

**Comment by olivierlacan** [comment]
It definitely would make sense to put the repo on Travis for good measure. :)

**Comment by olivierlacan** [comment]
Draper shows good example on how to test against [specific Rails versions](https://github.com/drapergem/draper/commit/1865ed3e3b2b34853689a60b59b8ce9145674d1d) and [even Edge Rails](https://github.com/drapergem/draper/commit/e9b71e3cf55a800b48c083ff257a7c1cbe1b601b), all of which seems to work beautifully with Travis.

**Comment by benhamill** [comment]
You know what. Fuck it. :wink: Let's do it live. I'm merging this.

**Comment by benhamill** [comment]
@olivierlacan: Thanks!

**Comment by olivierlacan** [comment]
Yay, thanks @benhamill :smile_cat:

**Comment by benhamill** [comment]
Note: Textacular 3.0.0 is out. So you may want to switch to that. Where all
future development will go on. :smile:

**Pull request merged**
